### ISSUE TITLE
( ios ) Can I change the runtime port? Just don't use the default one.

### ISSUE THREAD

**Issue by cloud-jie** [hackcatml/ajeossida#2]

**Comment by hackcatml** [comment]
Yes, you can change the default port 27042 by modifying the `frida/subprojects/frida-core/lib/base/socket.vala` file. 
But since frida-server already supports running on a different port using the -l option, I didn’t patch it. 
If you change the default port, you’ll need to set up port forwarding to attach to the app.

**Comment by hackcatml** [comment]
> Hello, it is true that the frida running port can be modified through the -l parameter, but frida will still run on the default port. I tried to uninstall frida, but it would remove related files. Later, I kept trying and moved the files to another unrelated directory in advance. When I ran it manually, it showed module not found. This can be solved by changing the CRYPTEX_MOUNT_PATH variable, but it is too troublesome. Is there any better way?
> 
> ![image](https://private-user-images.githubusercontent.com/63632785/384584398-1dca8dd8-e3be-4067-a7a3-f48f06284094.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzcxNDQsIm5iZiI6MTczMTEzNjg0NCwicGF0aCI6Ii82MzYzMjc4NS8zODQ1ODQzOTgtMWRjYThkZDgtZTNiZS00MDY3LWE3YTMtZjQ4ZjA2Mjg0MDk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDA3MjA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiYTdhYmExZWE5N2U5MTAyYzMwMzA0MjIxNjJmOTMxNGE0YWJhNWMxMjFmMzJlY2Y2MDRjNTY1MDUwMGRmYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LfDNkkV7mokKuG4bB4eUUOJPiC4vEwH0928hUPbDQ2w)


Remove original frida by `apt-get purge re.frida.server -y` and then install ajeossida.  
When changing the Frida port on an iOS device, unload the service first, modify the plist, and then load it again.  
- Unload
`launchctl unload /var/jb/Library/LaunchDaemons/re.ajeossida.server.plist`
- Modify plist
`vi /var/jb/Library/LaunchDaemons/re.ajeossida.server.plist`
![image](https://github.com/user-attachments/assets/ef0cf9c5-a183-48b8-906c-bf87339b2cc8)
- Load
`launchctl load /var/jb/Library/LaunchDaemons/re.ajeossida.server.plist`

Check `ps -ef | grep ajeossida`
![image](https://github.com/user-attachments/assets/fb9b58dc-863e-4736-966c-8d9c436dddf8)

Use Objection with the `-N`, `-h`, and `-p` options to attach to the remote device with the new port.  
![image](https://github.com/user-attachments/assets/7b8a7c0b-2cda-4009-b57a-c880810c3eff)
